import type { ImageConfig, LLMConfig, StyleTemplate } from "../types";

export type CatalogKind = "text" | "multimodal" | "image" | "video";

export interface ModelCatalogEntry {
  id: string;
  label: string;
  provider: string;
  base_url: string;
  model: string;
  kind: CatalogKind;
  note: string;
}

export const providerPresets: Record<string, Omit<LLMConfig, "api_key">> = {
  openai: {
    provider: "openai",
    base_url: "https://api.openai.com/v1",
    model: "gpt-5-mini",
    temperature: 0.6,
    max_tokens: 3000,
    top_p: 1,
  },
  ollama: {
    provider: "ollama",
    base_url: "http://localhost:11434/v1",
    model: "qwen3:8b",
    temperature: 0.6,
    max_tokens: 3000,
    top_p: 1,
  },
  deepseek: {
    provider: "deepseek",
    base_url: "https://api.deepseek.com/v1",
    model: "deepseek-chat",
    temperature: 0.6,
    max_tokens: 3000,
    top_p: 1,
  },
  zhipu: {
    provider: "zhipu",
    base_url: "https://open.bigmodel.cn/api/paas/v4",
    model: "glm-4.7-flash",
    temperature: 0.6,
    max_tokens: 3000,
    top_p: 1,
  },
  qwen: {
    provider: "qwen",
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    model: "qwen-plus",
    temperature: 0.6,
    max_tokens: 3000,
    top_p: 1,
  },
  minimax: {
    provider: "minimax",
    base_url: "https://api.minimaxi.com/v1",
    model: "MiniMax-M2.1",
    temperature: 0.6,
    max_tokens: 3000,
    top_p: 1,
  },
};

export const llmModelCatalog: ModelCatalogEntry[] = [
  {
    id: "openai-gpt-5.2",
    label: "OpenAI GPT-5.2",
    provider: "openai",
    base_url: "https://api.openai.com/v1",
    model: "gpt-5.2",
    kind: "text",
    note: "面向复杂推理、编码与代理任务。",
  },
  {
    id: "openai-gpt-5-mini",
    label: "OpenAI GPT-5 mini",
    provider: "openai",
    base_url: "https://api.openai.com/v1",
    model: "gpt-5-mini",
    kind: "text",
    note: "更快、更省成本，适合日常改写与调研。",
  },
  {
    id: "openai-gpt-4.1",
    label: "OpenAI GPT-4.1",
    provider: "openai",
    base_url: "https://api.openai.com/v1",
    model: "gpt-4.1",
    kind: "multimodal",
    note: "稳定的通用多模态模型，适合文本与图像理解。",
  },
  {
    id: "deepseek-chat",
    label: "DeepSeek Chat",
    provider: "deepseek",
    base_url: "https://api.deepseek.com/v1",
    model: "deepseek-chat",
    kind: "text",
    note: "通用中文写作与问答表现稳定。",
  },
  {
    id: "deepseek-reasoner",
    label: "DeepSeek Reasoner",
    provider: "deepseek",
    base_url: "https://api.deepseek.com/v1",
    model: "deepseek-reasoner",
    kind: "text",
    note: "更偏推理、分析与复杂问题拆解。",
  },
  {
    id: "zhipu-glm-4.7-flash",
    label: "智谱 GLM-4.7-Flash",
    provider: "zhipu",
    base_url: "https://open.bigmodel.cn/api/paas/v4",
    model: "glm-4.7-flash",
    kind: "text",
    note: "响应快，适合中文调研与 Agent 场景。",
  },
  {
    id: "qwen-plus",
    label: "通义千问 Qwen-Plus",
    provider: "qwen",
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    model: "qwen-plus",
    kind: "multimodal",
    note: "适合综合理解、问答与图文场景。",
  },
  {
    id: "qwen-max",
    label: "通义千问 Qwen-Max",
    provider: "qwen",
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    model: "qwen-max",
    kind: "text",
    note: "更强的综合生成与复杂任务能力。",
  },
  {
    id: "minimax-m2.1",
    label: "MiniMax M2.1",
    provider: "minimax",
    base_url: "https://api.minimaxi.com/v1",
    model: "MiniMax-M2.1",
    kind: "text",
    note: "长上下文与编码场景表现较强。",
  },
  {
    id: "ollama-qwen3-8b",
    label: "Ollama Qwen3 8B",
    provider: "ollama",
    base_url: "http://localhost:11434/v1",
    model: "qwen3:8b",
    kind: "multimodal",
    note: "本地部署友好，适合快速验证。",
  },
];

export const mediaModelCatalog: ModelCatalogEntry[] = [
  {
    id: "openai-gpt-image-1.5",
    label: "OpenAI GPT Image 1.5",
    provider: "openai",
    base_url: "https://api.openai.com/v1",
    model: "gpt-image-1.5",
    kind: "image",
    note: "OpenAI 当前主力图片生成模型。",
  },
  {
    id: "openai-gpt-image-1-mini",
    label: "OpenAI GPT Image 1 mini",
    provider: "openai",
    base_url: "https://api.openai.com/v1",
    model: "gpt-image-1-mini",
    kind: "image",
    note: "更经济，适合批量配图。",
  },
  {
    id: "gemini-imagen-4",
    label: "Google Imagen 4",
    provider: "gemini",
    base_url: "https://generativelanguage.googleapis.com/v1beta/openai/",
    model: "imagen-4.0-generate-001",
    kind: "image",
    note: "图片生成质量高，适合品牌视觉与插图。",
  },
  {
    id: "dashscope-wanx-2.1",
    label: "通义万相 Wanx 2.1",
    provider: "qwen",
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    model: "wanx2.1-t2i-turbo",
    kind: "image",
    note: "中文提示词友好，适合海报与插画。",
  },
  {
    id: "openai-sora-2",
    label: "OpenAI Sora 2",
    provider: "openai",
    base_url: "https://api.openai.com/v1",
    model: "sora-2",
    kind: "video",
    note: "视频生成参考模型；当前主流程仍以文本/图片为主。",
  },
  {
    id: "openai-sora-2-pro",
    label: "OpenAI Sora 2 Pro",
    provider: "openai",
    base_url: "https://api.openai.com/v1",
    model: "sora-2-pro",
    kind: "video",
    note: "更高质量的视频生成参考配置。",
  },
];

export const imageProviderPresets: Record<string, Partial<ImageConfig>> = {
  openai: {
    provider: "openai",
    base_url: "https://api.openai.com/v1",
    model: "gpt-image-1.5",
  },
  gemini: {
    provider: "gemini",
    base_url: "https://generativelanguage.googleapis.com/v1beta/openai/",
    model: "imagen-4.0-generate-001",
  },
  qwen: {
    provider: "qwen",
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    model: "wanx2.1-t2i-turbo",
  },
};

export const defaultStyles: StyleTemplate[] = [
  {
    id: "humor",
    name: "幽默风趣",
    prompt:
      "轻松幽默但不油腻；保留关键事实与结论；先给 TL;DR（3~6 条），再分节展开；多用小标题/列表，少口水。",
    audience: "公众号读者 / 泛科技读者",
    tone: "轻快、机灵、信息密度高",
    structure_template: "TL;DR -> 分节解析 -> 结尾总结",
    emphasis_points: ["关键事实", "核心结论", "易读性"],
    citation_policy: "minimal",
    title_policy: "punchy",
    image_focus: "editorial",
    layout_format: "auto",
    visual_mode: "minimal",
  },
  {
    id: "outline",
    name: "简明大纲",
    prompt:
      "输出结构化大纲：TL;DR（3~6 条）→ 主题分节（每节 3~5 要点）→ 结论/行动建议；信息密度高，避免空话。",
    audience: "需要快速掌握要点的读者",
    tone: "克制、清晰、结构优先",
    structure_template: "TL;DR -> 主题分节 -> 结论/行动建议",
    emphasis_points: ["结构完整", "重点前置", "行动建议"],
    citation_policy: "auto",
    title_policy: "retain",
    image_focus: "diagram",
    layout_format: "auto",
    visual_mode: "enhanced",
  },
  {
    id: "kids",
    name: "儿童友好",
    prompt:
      "面向中学生：用简单句解释复杂概念，保持准确；先用 5 句话讲清主题，再用要点列表展开；避免术语堆砌，必要时做类比。",
    audience: "中学生 / 初学者",
    tone: "耐心、友好、具象",
    structure_template: "5 句讲清主题 -> 要点列表 -> 生活化类比",
    emphasis_points: ["准确解释", "降低门槛", "类比表达"],
    citation_policy: "none",
    title_policy: "rewrite",
    image_focus: "narrative",
    layout_format: "auto",
    visual_mode: "minimal",
  },
  {
    id: "newspaper",
    name: "报纸特稿",
    prompt:
      "按报纸特稿排版写作：导语先交代核心事实，再以多栏新闻分析风格展开；标题准确有力度，小标题短促清晰，段落紧凑。",
    audience: "新闻读者 / 研究读者",
    tone: "冷静、凝练、判断明确",
    structure_template: "导语 -> 核心事实 -> 分栏分析 -> 结语",
    emphasis_points: ["关键事实", "背景脉络", "判断结论"],
    citation_policy: "strict",
    title_policy: "rewrite",
    image_focus: "editorial",
    layout_format: "newspaper",
    visual_mode: "minimal",
  },
  {
    id: "poster",
    name: "海报解读",
    prompt:
      "写成适合海报/长图阅读的内容：大标题强、结论前置、每节短而有冲击力，适合搭配统计卡、流程图和重点标语。",
    audience: "社媒读者 / 展示场景",
    tone: "醒目、利落、节奏感强",
    structure_template: "大标题 -> 一句话结论 -> 重点卡片 -> 行动建议",
    emphasis_points: ["一句话结论", "重点数字", "流程步骤"],
    citation_policy: "minimal",
    title_policy: "punchy",
    image_focus: "editorial",
    layout_format: "poster",
    visual_mode: "enhanced",
  },
  {
    id: "book",
    name: "书籍章节",
    prompt:
      "写成书籍章节式排版：结构完整，叙述沉稳，段落过渡自然，可加入图表、术语解释和节中摘要，适合长阅读。",
    audience: "深度阅读者",
    tone: "沉稳、清晰、耐读",
    structure_template: "章节摘要 -> 分节正文 -> 图表/案例 -> 章节总结",
    emphasis_points: ["完整叙述", "关键概念", "图表辅助"],
    citation_policy: "strict",
    title_policy: "retain",
    image_focus: "diagram",
    layout_format: "book",
    visual_mode: "enhanced",
  },
  {
    id: "classical-book",
    name: "古文书卷",
    prompt:
      "写成有古籍书卷气的现代中文整理稿：语言典雅但可读，段落留白更克制，可保留原意并加入简短题解、注解和纲目。",
    audience: "人文 / 古典阅读者",
    tone: "雅致、含蓄、从容",
    structure_template: "题解 -> 纲目 -> 正文 -> 按语",
    emphasis_points: ["题解", "纲目", "注解说明"],
    citation_policy: "minimal",
    title_policy: "retain",
    image_focus: "narrative",
    layout_format: "classical",
    visual_mode: "minimal",
  },
  {
    id: "story",
    name: "故事风",
    prompt:
      "改写成故事化表达：先给读者一个具象场景或冲突，再按起因、转折、启发推进；保留事实，不要虚构关键细节。",
    audience: "泛读者 / 内容平台读者",
    tone: "有画面感、顺滑、代入感强",
    structure_template: "引子 -> 关键冲突 -> 过程展开 -> 启发总结",
    emphasis_points: ["场景感", "情节推进", "关键事实"],
    citation_policy: "minimal",
    title_policy: "rewrite",
    image_focus: "narrative",
    layout_format: "book",
    visual_mode: "minimal",
  },
  {
    id: "ppt",
    name: "PPT 汇报",
    prompt:
      "写成适合 PPT / 汇报页直接复用的内容：一屏一重点，短句、标题党式小结论、要点列表和行动建议更明确，避免大段连写。",
    audience: "汇报对象 / 管理层 / 项目评审",
    tone: "简练、结论先行、适合投屏",
    structure_template: "封面结论 -> 关键数据 -> 方案对比 -> 行动项",
    emphasis_points: ["一句话结论", "关键数据", "行动项"],
    citation_policy: "minimal",
    title_policy: "punchy",
    image_focus: "diagram",
    layout_format: "ppt",
    visual_mode: "enhanced",
  },
  {
    id: "paper",
    name: "论文风",
    prompt:
      "写成学术论文/研究综述风格：先摘要，再交代问题、分析方法、论证过程和结论；术语准确，表达克制，必要处保留引用。",
    audience: "研究者 / 学术型读者",
    tone: "严谨、克制、论证清楚",
    structure_template: "摘要 -> 背景 -> 分析 -> 讨论 -> 结论",
    emphasis_points: ["研究问题", "论据链", "结论边界"],
    citation_policy: "strict",
    title_policy: "retain",
    image_focus: "diagram",
    layout_format: "paper",
    visual_mode: "enhanced",
  },
  {
    id: "briefing",
    name: "商业简报",
    prompt:
      "写成适合管理层快速决策的商业简报：一句话结论前置，再给关键数据、核心判断、风险与建议；避免情绪化铺陈。",
    audience: "管理层 / 项目负责人 / 决策者",
    tone: "冷静、结论先行、适合决策",
    structure_template: "一句话结论 -> 关键数据 -> 核心判断 -> 风险与建议",
    emphasis_points: ["一句话结论", "关键数据", "决策建议"],
    citation_policy: "minimal",
    title_policy: "retain",
    image_focus: "diagram",
    layout_format: "ppt",
    visual_mode: "enhanced",
  },
  {
    id: "manual",
    name: "教程手册",
    prompt:
      "写成可照着执行的教程/手册：先讲目标和前置条件，再按步骤展开，并补充常见问题、排错提示与完成标准。",
    audience: "实操读者 / 执行者 / 初中级用户",
    tone: "清楚、务实、可执行",
    structure_template: "目标 -> 前置条件 -> 步骤 -> 排错 -> 总结",
    emphasis_points: ["步骤顺序", "前置条件", "排错提示"],
    citation_policy: "minimal",
    title_policy: "retain",
    image_focus: "diagram",
    layout_format: "book",
    visual_mode: "enhanced",
  },
  {
    id: "speech",
    name: "演讲稿",
    prompt:
      "写成适合朗读的演讲稿：开场先定调，再用 2~4 个核心论点推进，结尾要有收束和号召；句子要有节奏，不要写成长段说明书。",
    audience: "听众 / 路演观众 / 会议现场",
    tone: "有感染力、顺口、节奏清晰",
    structure_template: "开场定调 -> 核心论点 -> 例证/转折 -> 收束号召",
    emphasis_points: ["开场抓人", "论点推进", "收束号召"],
    citation_policy: "minimal",
    title_policy: "punchy",
    image_focus: "editorial",
    layout_format: "ppt",
    visual_mode: "minimal",
  },
  {
    id: "interview",
    name: "访谈问答",
    prompt:
      "写成访谈/问答稿：以问题驱动展开，把复杂内容拆成提问、回答与追问，保留观点交锋感，但不要编造对话细节。",
    audience: "内容平台读者 / 访谈节目受众",
    tone: "自然、清楚、有来有回",
    structure_template: "引题 -> 问题 -> 回答 -> 追问 -> 小结",
    emphasis_points: ["问题设计", "回答重点", "观点交锋"],
    citation_policy: "minimal",
    title_policy: "rewrite",
    image_focus: "narrative",
    layout_format: "book",
    visual_mode: "minimal",
  },
  {
    id: "editorial",
    name: "评论社论",
    prompt:
      "写成评论/社论风：立场要清楚，先给判断，再用事实依据与分析支撑，最后收束到观点与建议；不要空喊口号。",
    audience: "观点型读者 / 时评读者",
    tone: "有立场、克制、判断明确",
    structure_template: "观点 -> 事实依据 -> 分析推进 -> 结论与建议",
    emphasis_points: ["明确判断", "事实依据", "观点收束"],
    citation_policy: "strict",
    title_policy: "rewrite",
    image_focus: "editorial",
    layout_format: "newspaper",
    visual_mode: "minimal",
  },
  {
    id: "documentary",
    name: "纪实风",
    prompt:
      "写成纪实/非虚构风格：先交代人物、现场或时间线，再按事实脉络推进；语言克制，细节要真实，不要虚构情节或拔高情绪。",
    audience: "深度内容读者 / 纪实阅读者",
    tone: "克制、具体、现场感强",
    structure_template: "现场切入 -> 事实脉络 -> 人物/背景 -> 余波与判断",
    emphasis_points: ["事实脉络", "现场细节", "人物与背景"],
    citation_policy: "strict",
    title_policy: "rewrite",
    image_focus: "editorial",
    layout_format: "newspaper",
    visual_mode: "minimal",
  },
  {
    id: "letter",
    name: "书信风",
    prompt:
      "改写成书信/公开信风格：要有称呼、缘起、展开和收束，像认真写给某个对象；保留事实与观点，但不要写成报告或公告。",
    audience: "目标读者 / 被说服对象 / 公开读者",
    tone: "真诚、从容、有对象感",
    structure_template: "称呼与缘起 -> 主体展开 -> 重点叮嘱 -> 收束致意",
    emphasis_points: ["对象感", "重点叮嘱", "收束语气"],
    citation_policy: "minimal",
    title_policy: "rewrite",
    image_focus: "narrative",
    layout_format: "book",
    visual_mode: "minimal",
  },
  {
    id: "podcast",
    name: "播客口播",
    prompt:
      "写成适合播客或口播朗读的内容：开场先拉住听众，再顺着主题自然展开；句子要口语化、有停顿感，方便一口气读出来。",
    audience: "听众 / 节目观众 / 口播场景",
    tone: "自然、顺口、有陪伴感",
    structure_template: "开场引题 -> 主线展开 -> 转折补充 -> 收束与提问",
    emphasis_points: ["开场抓人", "口语节奏", "自然转场"],
    citation_policy: "minimal",
    title_policy: "rewrite",
    image_focus: "narrative",
    layout_format: "book",
    visual_mode: "minimal",
  },
  {
    id: "debate",
    name: "辩论风",
    prompt:
      "写成有攻防感的辩论稿：先亮明主张，再分点论证、回应反方，再回到结论；逻辑必须清楚，不能只有情绪和口号。",
    audience: "辩论观众 / 观点型读者 / 课堂场景",
    tone: "锋利、克制、逻辑推进明确",
    structure_template: "主张 -> 论点一二三 -> 反方回应 -> 结论收束",
    emphasis_points: ["核心主张", "论点攻防", "结论收束"],
    citation_policy: "strict",
    title_policy: "punchy",
    image_focus: "diagram",
    layout_format: "ppt",
    visual_mode: "minimal",
  },
  {
    id: "poetry",
    name: "诗歌风",
    prompt:
      "写成现代诗/散文诗风格：以节奏、意象和留白组织内容，但核心事实不能失真；可短句分行，避免解释腔过重。",
    audience: "文艺读者 / 情绪表达场景",
    tone: "凝练、抒情、留白感强",
    structure_template: "意象开场 -> 分段递进 -> 回响式收束",
    emphasis_points: ["意象", "节奏", "核心主旨"],
    citation_policy: "none",
    title_policy: "rewrite",
    image_focus: "narrative",
    layout_format: "poetry",
    visual_mode: "none",
  },
  {
    id: "science",
    name: "科普风",
    prompt:
      "写成高质量科普解读：先用一句话讲清核心，再拆成常见问题、原理解释、误区提醒和现实意义；尽量用类比帮助理解。",
    audience: "普通读者 / 初学者",
    tone: "耐心、清楚、不装深奥",
    structure_template: "一句话概括 -> 常见问题 -> 原理解释 -> 误区提醒",
    emphasis_points: ["核心原理", "误区纠正", "现实意义"],
    citation_policy: "minimal",
    title_policy: "rewrite",
    image_focus: "diagram",
    layout_format: "auto",
    visual_mode: "enhanced",
  },
  {
    id: "elegant",
    name: "文雅风",
    prompt:
      "写成文雅、从容、富有修辞感的现代中文；句式可更舒展，但不能故作艰深，仍需保证逻辑清楚、事实准确。",
    audience: "人文类读者",
    tone: "雅致、从容、克制",
    structure_template: "起笔铺垫 -> 分层展开 -> 收束余味",
    emphasis_points: ["修辞质感", "层次感", "准确表达"],
    citation_policy: "minimal",
    title_policy: "rewrite",
    image_focus: "narrative",
    layout_format: "book",
    visual_mode: "minimal",
  },
  {
    id: "plain",
    name: "通俗风",
    prompt:
      "写得通俗易懂：多用短句和口语化解释，把术语换成日常说法；先讲结论，再讲原因，避免书面腔和绕弯。",
    audience: "大众读者",
    tone: "直接、易懂、生活化",
    structure_template: "先讲结论 -> 分点解释 -> 最后提醒",
    emphasis_points: ["好懂", "结论前置", "少术语"],
    citation_policy: "minimal",
    title_policy: "rewrite",
    image_focus: "auto",
    layout_format: "auto",
    visual_mode: "minimal",
  },
  {
    id: "childish",
    name: "幼稚童趣",
    prompt:
      "写成带童趣的表达：句子短、比喻简单、情绪明亮，像讲给小朋友听；不要改变事实，只把表达变得更天真可爱。",
    audience: "儿童 / 亲子场景",
    tone: "天真、活泼、可爱",
    structure_template: "一句话开场 -> 小段落解释 -> 温柔收尾",
    emphasis_points: ["可爱感", "短句", "简单比喻"],
    citation_policy: "none",
    title_policy: "rewrite",
    image_focus: "narrative",
    layout_format: "poster",
    visual_mode: "minimal",
  },
  {
    id: "cheerful",
    name: "欢乐风",
    prompt:
      "写得更欢乐、更有分享欲：节奏明快，情绪向上，适度加入轻松吐槽或惊喜感，但不要油腻、不要夸大事实。",
    audience: "社媒读者 / 年轻用户",
    tone: "明快、轻松、带感染力",
    structure_template: "亮眼开头 -> 重点展开 -> 轻快收束",
    emphasis_points: ["分享欲", "节奏感", "记忆点"],
    citation_policy: "minimal",
    title_policy: "punchy",
    image_focus: "editorial",
    layout_format: "poster",
    visual_mode: "enhanced",
  },
  {
    id: "riddle",
    name: "猜谜风",
    prompt:
      "写成带悬念和猜谜感的内容：开头先留问题或线索，再逐步揭晓答案；节奏上有铺垫和反转，但不能故弄玄虚。",
    audience: "互动内容读者",
    tone: "悬念感、机巧、好玩",
    structure_template: "抛出谜面 -> 给线索 -> 揭晓答案 -> 点题",
    emphasis_points: ["悬念", "线索设计", "揭晓瞬间"],
    citation_policy: "minimal",
    title_policy: "punchy",
    image_focus: "narrative",
    layout_format: "poster",
    visual_mode: "minimal",
  },
  {
    id: "snack",
    name: "快餐风",
    prompt:
      "写成碎片化快读内容：结论极前置，短段落、高密度 bullet、适合手机快速扫读；删掉铺垫，只保留最有用的信息。",
    audience: "移动端快读用户",
    tone: "直接、干脆、信息量大",
    structure_template: "一句话结论 -> 3~5 个重点 -> 行动建议",
    emphasis_points: ["速读", "重点", "可执行"],
    citation_policy: "minimal",
    title_policy: "punchy",
    image_focus: "diagram",
    layout_format: "poster",
    visual_mode: "enhanced",
  },
];

export const imageStylePresets = ["童话绘本", "科技感", "水墨画", "卡通", "写实", "概念图"];
